version: "3"
services: 
  goapp: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    tty: true # コンテナの永続化
    cap_add:
    - NET_ADMIN
    volumes:
      - ../:/go/src/app # マウントディレクトリ
    networks:
      test-tc:
        ipv4_address: 192.168.10.6
    labels:
      - "io.kubernetes.pod.name=edge-0"
  test1:
    image: alpine
    tty: true # コンテナの永続化
    networks:
      test-tc:
        ipv4_address: 192.168.10.10
    labels:
      - "io.kubernetes.pod.name=edge-1"
  test2:
    image: alpine
    tty: true # コンテナの永続化
    networks:
      test-tc:
        ipv4_address: 192.168.10.20
    labels:
      - "io.kubernetes.pod.name=edge-2"
  test3:
    image: alpine
    tty: true # コンテナの永続化
    networks:
      test-tc:
        ipv4_address: 192.168.10.30
    labels:
      - "io.kubernetes.pod.name=edge-3"
  test4:
    image: alpine
    tty: true # コンテナの永続化
    networks:
      test-tc:
        ipv4_address: 192.168.10.40
    labels:
      - "io.kubernetes.pod.name=edge-4"
  test5:
    image: alpine
    tty: true # コンテナの永続化
    networks:
      test-tc:
        ipv4_address: 192.168.10.50
    labels:
      - "io.kubernetes.pod.name=edge-5"
networks:
  test-tc:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16