apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edge-emulate
  namespace: edge-emulate
spec:
  selector:
    matchLabels:
      app: edge-emulate
  template:
    metadata:
      labels:
        app: edge-emulate
        name: edge-emulate
    spec:
      containers:
      - image: supercord530/edge-emulate:flute
        imagePullPolicy: Always
        name: delay
        args:
          - delay
          - --tc-image
          - supercord530/iproute2:flute
          - set 
          - -f 
          - ../mount/latency.json
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: dockersocket
          - mountPath: /mount
            name: config
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        - name: config
          configMap:
            name: setting-latency